# Generated by Django 3.1.3 on 2021-02-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokendetails',
            old_name='status',
            new_name='statestatus',
        ),
    ]
