# Generated by Django 3.1.3 on 2021-02-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server1', '0002_auto_20210207_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendetails',
            name='userpk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
