# Generated by Django 3.1.3 on 2021-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server1', '0004_auto_20210207_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendetails',
            name='userpk',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
