# Generated by Django 3.1.3 on 2021-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server1', '0005_auto_20210207_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendetails',
            name='userpk',
            field=models.CharField(max_length=50),
        ),
    ]
